--logo arch
--logo-color-1 blue
--logo-color-2 blue

--color blue
--separator ": "

--set-keyless Monoline="""""""""""

--set-keyless Software=┌───────── \e[1mSoftware Information \e[0m─────────
--set-keyless Hardware=├───────── \e[1mHardware Information \e[0m─────────
--set-keyless End=└────────────────────────────────────────

--os-key "| OS"
--host-key "| Host"
--kernel-key "| Kernel"
--uptime-key "| Uptime"
--packages-key "| Packages"
--shell-key "| Shell"
--wm-key "| WM"

--gpu-key "| GPU0"
--cpu-key "| CPU"
--memory-key "| Memory"
--terminal-key "| Terminal"
--theme-key "| Theme"
--display-key "| Display (VGA1)"
--locale-key "| Locale"
--structure Title:Monoline:Software:OS:Kernel:Packages:Shell:WM:Terminal:Theme:Hardware:Host:Display:CPU:GPU:Memory:End
