[Berke]
source        = imaps+xoauth2://berkeerbagci%40outlook.com:t4PjdR6Cz554@outlook.office365.com:993
outgoing      = smtp+xoauth2://berkeerbagci%40outlook.com:t4PjdR6Cz554@smtp-mail.outlook.com:587
default       = INBOX
from          = Berke Erbağcı <berkeerbagci@outlook.com>
cache-headers = true
