
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# For a sample file, please refer to https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/userprefs.t2

# monitor = ,preferred,auto,auto
# before binding should use unbind, see https://wiki.hyprland.org/Configuring/Binds/#unbind
bind = $mainMod, M, exec, betterbird

bind = $mainMod, F5, exec, wlsunset -T 6500
bind = $mainMod, F6, exec, pkill wlsunset 
bind = $mainMod, O, exec, obsidian # launch obsidian
bind = $mainMod, y, exec, grim -g "$(slurp)" - | tesseract - - -l tur+eng+jpn | wl-copy #Grab text from screen

# Media control
bindl  = , XF86AudioPlay, exec, playerctl play-pause # toggle between media play and pause
bindl  = , XF86AudioPause, exec, playerctl play-pause # toggle between media play and pause
bindl  = , XF86AudioNext, exec, playerctl next # media next
bindl  = , XF86AudioPrev, exec, playerctl previous # media previous

# Move/Change window focus
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Resize windows
binde = $mainMod+Shift, L, resizeactive, 30 0
binde = $mainMod+Shift, H, resizeactive, -30 0
binde = $mainMod+Shift, K, resizeactive, 0 -30
binde = $mainMod+Shift, J, resizeactive, 0 30

bind = $mainMod+Ctrl, L, exec, swaylock # launch lock screen
bind = $mainMod+Ctrl, J, togglesplit
bind = $mainMod+Ctrl, K, exec, $scrPath/keyboardswitch.sh # switch keyboard layout
bind = $mainMod+Shift, U, exec, Hyde show emoji #Open Emoji Picker using rofi
bind = , XF86Calculator, exec, Hyde show calc #Open Calculator using rofi
bind = , XF86Messenger, exec, Hyde show calc #Open Calculator using rofi

# Move active window around current workspace with mainMod + SHIFT + CTRL [HJKL]
$moveactivewindow=grep -q "true" <<< $(hyprctl activewindow -j | jq -r .floating) && hyprctl dispatch moveactive
binded = $mainMod SHIFT $CONTROL, H,Move activewindow to the left,exec, $moveactivewindow -30 0 || hyprctl dispatch movewindow l
binded = $mainMod SHIFT $CONTROL, L,Move activewindow to the right,exec, $moveactivewindow 30 0 || hyprctl dispatch movewindow r
binded = $mainMod SHIFT $CONTROL, K,Move activewindow to the up,exec, $moveactivewindow  0 -30 || hyprctl dispatch movewindow u
binded = $mainMod SHIFT $CONTROL, J,Move activewindow to the down,exec, $moveactivewindow 0 30 || hyprctl dispatch movewindow d

