# Open a new tab named "Debian Server"
new_tab Debian Server
layout splits

# Initiate the first connection
launch kitten ssh berke@192.168.1.100

# Create a vertical split and connect again
launch --location=vsplit kitten ssh berke@192.168.1.100 

# Create a horizontal split below the second one and connect again
launch --location=hsplit kitten ssh berke@192.168.1.100
