let mapleader = " "

syntax on "parser

filetype plugin indent on

set number
set relativenumber

" nvim defaults
set tabstop=4        
set shiftwidth=4     
set expandtab        

set hlsearch "hilight search, :nohl to remove

set t_Co=256 "terminal colors

set wildmenu " auto completion, trigger with <C-n> 


let s:VIM_DIR = fnamemodify($MYVIMRC, ':h')
if filereadable(s:VIM_DIR . '/colors/wallbash.vim')
    colorscheme wallbash
endif

let s:VIM_DIR = fnamemodify($MYVIMRC, ':h')
execute 'source ' . s:VIM_DIR . '/hyde.vim'

" Adding your custom colorschem
colorscheme habamax "the only nice built-in colorscheme 

nnoremap L $
nnoremap H _
vnoremap L $
vnoremap H _
