
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# For a sample file, please refer to https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/userprefs.t2

workspace = 1, default:true,monitor:DP-3
workspace = 2, monitor:HDMI-A-1

input {
    repeat_delay = 250
    kb_layout = tr,tr
    kb_variant = alt,basic
    kb_options = grp:win_space_toggle
}
cursor{
    default_monitor = DP-3
}

exec-once = dex -a
exec-once = /opt/localsend/localsend --hidden
exec-once = /usr/bin/kdeconnectd 
exec-once = kdeconncet-indicator
exec-once = brightness init
exec-once = jellyfin-mpv-shim
exec-once = xrandr --output DP-3 --primary
exec-once = hyde-shell pypr toggle console


input:touchpad {
    natural_scroll = true
}

# Persistent gaming mode
animations {
    enabled  = 0
}
general{
    gaps_in = 2
    gaps_out = 5
    border_size = 1
}
decoration{
    rounding = 12
    active_opacity = 1
    inactive_opacity = 1
    fullscreen_opacity = 1 
    blur:xray = 0
    blur:enabled = 0
    shadow:enabled = 0
}
xwayland {
  force_zero_scaling = true
}
