[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\v/home/berke)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\vT\0\0\x1\xfe\0\0\r8\0\0\x3\xb6\0\0\vT\0\0\x1\xfe\0\0\r8\0\0\x3\xb6\0\0\0\0\0\0\0\0\n\0\0\0\vT\0\0\x1\xfe\0\0\r8\0\0\x3\xb6)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(600 339)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/berke/Downloads/RDT_20260218_020100.mp4
times=0
