[[mgr.prepend_keymap]]
on = "i"
run = "rename --cursor=before_ext"
desc = "Rename hovered/selected"

[[mgr.prepend_keymap]]
on = "a"
run = "rename --cursor=before_ext"
desc = "Rename hovered/selected"

[[mgr.prepend_keymap]]
on = "o"
run = "create"
desc = "Create file or directory"

[[mgr.prepend_keymap]]
on   = [ "b", "l" ]
run  = "cd sftp://beelink"
desc = "Go to home server"

[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

# [[mgr.prepend_keymap]]
# on = "<Enter>"
# run = "enter"
# desc = "Enter child directory"
