[[mgr.prepend_keymap]]
on = "i"
run = "rename --cursor=before_ext"
desc = "Rename hovered/selected"

[[mgr.prepend_keymap]]
on = "a"
run = "rename --cursor=before_ext"
desc = "Rename hovered/selected"

[[mgr.prepend_keymap]]
on = "o"
run = "create"
desc = "Create file or directory"

[[mgr.prepend_keymap]]
on   = [ "b", "l" ]
run  = "cd sftp://beelink"
desc = "Go to home server"
