[mgr]
show_hidden = true
linemode = "size_and_mtime"

[opener]
zathura = [
	{ run = 'zathura "$@"', orphan = true, desc = "zathura",  for = "unix" },
	]
[open]
rules = [
	{ mime = "application/pdf", use = [ "zathura", "reveal" ] }
]
