[General]
appAutoLocking=false
app_install_time=1776094518
app_launched_count=17
autoLockDuration=30
firstrun_tray=false
geometry="@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\n\0\0\0\x1,\0\0\f\t\0\0\x5+\0\0\n\0\0\0\x1,\0\0\r\xb6\0\0\x5+\0\0\0\0\x2\0\0\0\a\x80\0\0\n\0\0\0\x1,\0\0\f\t\0\0\x5+)"
lockscreen=false
notificationCombo=1
notificationTimeOut=5000
rated_already=true
settingsGeo="@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\n\0\0\0\x1,\0\0\xe\x99\0\0\x4\xc9\0\0\n\0\0\0\x1,\0\0\x11s\0\0\x5+\0\0\0\0\x2\0\0\0\a\x80\0\0\n\0\0\0\x1,\0\0\xe\x99\0\0\x4\xc9)"
widgetStyle=Fusion
windowTheme=dark

[permissions]
7=true
Notifications=true
