[General]
appAutoLocking=false
app_install_time=1776094518
app_launched_count=54
autoLockDuration=30
disableNotificationPopups=true
firstrun_tray=false
geometry="@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\n\0\0\0\x1,\0\0\x11s\0\0\x5+\0\0\n\0\0\0\x1,\0\0\x11s\0\0\x5+\0\0\0\0\x2\0\0\0\a\x80\0\0\n\0\0\0\x1,\0\0\x11s\0\0\x5+)"
lockscreen=false
notificationCombo=0
notificationTimeOut=5000
rated_already=true
settingsGeo="@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\n\0\0\0\x1,\0\0\xf\x45\0\0\x4\xbb\0\0\n\0\0\0\x1,\0\0\x11s\0\0\x5+\0\0\0\0\x2\0\0\0\a\x80\0\0\n\0\0\0\x1,\0\0\xf\x45\0\0\x4\xbb)"
useNativeFileDialog=false
widgetStyle=Fusion
windowTheme=dark

[permissions]
7=true
Notifications=true
