-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "DP-3", mode = "2560x1440@144.006", position = "0x0", scale = 1, vrr = 0 })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60.000", position = "2560x300", scale = 1, vrr = 0 })
