[pyprland]
    plugins = [ "scratchpads" ]

[pyprland.variables]
    term_with_class = "kitty --class"

[scratchpads.console]
    animation = "fromTop"
    class     = "console-dropdown"
    command   = "[term_with_class] console-dropdown"
    max_size  = "90% 50%"
    size      = "75% 50%"
